#!/usr/bin/env python

import socket

UDP_IP = "10.0.0.11"
UDP_PORT = 44444
sock = socket.socket(socket.AF_INET,socket.SOCK_DGRAM)
sock.bind((UDP_IP, UDP_PORT))
while True:
    print "start"
   # data, addr = sock.recvfrom(512)
    print "received message from roach2:", sock.recv(1024)
sock.close()
